language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t amirinbar/todo-app-docker-vue -f Dockerfile.dev .

script:
  - docker run -e CI=true amirinbar/todo-app-docker-vue npm run test