sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t amirinbar/todo-app-docker-vue -f Dockerfile.dev .

script:
  - docker run -e CI=true amirinbar/todo-app-docker-vue npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "todo-app-docker-vue"
    env: "Todoappdockervue-env-1"
    bucket_name: "elasticbeanstalk-us-east-1-258435333577"
    bucket_path: "todo-app-docker-vue"
    on:
        branch: main
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
